version: "3"
services:
  wpmastersvc:
    container_name: "wp-master-svc"
    build: ./mastersvc
    ports:
      - "8090:8090"
  wptransactionsvc:
    container_name: "wp-transaction-svc"
    build: ./transactionsvc
    ports:
      - "8091:8091"
